- name: Install ubuntu-desktop (apt)
  become: true
  become_user: "{{ root_user }}"
  apt:
      name: "{{item}}"
      state: latest
  with_items:
      - ubuntu-desktop
      #- lxde
      #- lxde-common
  notify: apt clean

- name: Install packages (pip)
  become: true
  become_user: "{{ root_user }}"
  pip:
      name: "{{item}}"
      state: latest
  with_items:
      - psutil

- name: Start gdm3 service to get a graphical login
  become: true
  become_user: "{{ root_user }}"
  service:
    name: gdm3
    state: started

- name: install chromium-browser
  become: true
  become_user: "{{ root_user }}"
  apt:
      name: "chromium-browser"
      state: latest
  notify: apt clean
  when: ubuntu_desktop_browser == 'chromium-browser'

- name: 
  include_role: 
    name: gantsign.default-web-browser
  vars:
    default_web_browser: chromium-browser
  when: ubuntu_desktop_browser == 'chromium-browser'
